# Generated by Django 4.2.2 on 2023-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_remove_news_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
