# Generated by Django 4.2.2 on 2023-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_rename_description_news_text_rename_name_news_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='time_in',
        ),
        migrations.AddField(
            model_name='news',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
